### ISSUE TITLE
Custom Auth Model

### ISSUE THREAD

**Issue by ghaffaru** [anexia-it/django-rest-passwordreset#102]
How do I set a custom model to be used for the password reset flow ?

**Comment by jamehii** [comment]
Make sure your settings.py sets the following:

AUTH_USER_MODEL = YourCustomUserModel

**Comment by Ghaffaru15** [comment]
I have already set it for an initial custom model.
How do i set another customer user model in the same project ?

**Comment by jamehii** [comment]
As far as I know, django settings.py has only one AUTH_USER_MODEL... can't set more than one unless creating another new project folder

**Comment by anx-cbenke** [comment]
@ghaffaru can we close this issue or do you need further assistance?

**Comment by anx-hnezbeda** [comment]
The project currently supports the Dajngo User Model, which can be customized/extended and replaced by the AUTH_USER_MODEL setting. From your description it seems that your are using a dedicated model with an additional authentication backend for the customers.

**Comment by ghaffaru** [comment]
Closing the issue now.
I implemented the password reset from scratch, since I couldnt use this package for two different Auth Models in the same project
