### ISSUE TITLE
Is django-rest-passwordreset safe to use on django 3.*.*

### ISSUE THREAD

**Issue by yibizzi** [anexia-it/django-rest-passwordreset#109]
If not, are there any alternatives?

**Comment by rnegron** [comment]
If you try to use it, the following exception will occur:

```
File "/usr/local/lib/python3.7/site-packages/django_rest_passwordreset/models.py", line 3, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/usr/local/lib/python3.7/site-packages/django/utils/encoding.py
```

This is because Django 3.0 [removed Python 2 compatability](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis). So no, this package is not safe to use on Django 3.0

**Comment by anx-cbenke** [comment]
Coincidentally, I've just been working on the version update these days. We'll update the compatibility matrix shortly! And yes, Django 3.x will work fine and safe!

**Comment by yibizzi** [comment]
Great. Thanks mates.
I'll close the issue.
