### ISSUE TITLE
Email not being sent

### ISSUE THREAD

**Issue by ReaperZ0v** [anexia-it/django-rest-passwordreset#131]
Followed documented instructions yet the token prints on the console but no email is sent. (yes the email settings have been adjusted in settings.py)

**Comment by AlphaSh0w** [comment]
If the mail is printing to the console, doesn't that mean that your "EMAIL_BACKEND" setting in settings.py is set to "django.core.mail.backends.console.EmailBackend" ?
if that's the case you need to change it to the proper backend for your email provider.
