### ISSUE TITLE
Warnings on deprecated libs when running tests

### ISSUE THREAD

**Issue by Younext19** [anexia-it/django-rest-passwordreset#133]
/usr/local/lib/python3.8/site-packages/django_rest_passwordreset/models.py:44: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    verbose_name=_("The User which is associated to this password reset token")

 i am getting many errors such like this one when i run my tests using pytest,
it will create a problem or smth ? i think you should upgrade the library

**Comment by nezhar** [comment]
This will be a problem form Django 4.0 onwards as `ugettext_lazy` has been deprecated. We just release version `1.2.0` which includes the fix the Django 4.0 deprecations: https://github.com/anexia-it/django-rest-passwordreset/pull/83
