### ISSUE TITLE
Password validation doesn't exist.

### ISSUE THREAD

**Issue by buurak** [anexia-it/django-rest-passwordreset#135]
**password1
password2** 
may be asked for validation.

**Comment by nezhar** [comment]
Thank for your suggestion, but I would recommend to implement such a validation task on client side, as this is out of scope for the password reset endpoint.

**Comment by io-ma** [comment]
I think password validation should defo exist at Django level too.

**Comment by nezhar** [comment]
@io-ma this is a simple comparison that can be done on client side, there is no real benefit of adding such a restriction in the REST API.

**Comment by io-ma** [comment]
My bad, just saw password validation was added to Django in this view:
[https://github.com/anexia-it/django-rest-passwordreset/blob/master/django_rest_passwordreset/views.py](https://github.com/anexia-it/django-rest-passwordreset/blob/master/django_rest_passwordreset/views.py)
