### ISSUE TITLE
How to send a reset token without the user using the endpoint

### ISSUE THREAD

**Issue by cyzanfar** [anexia-it/django-rest-passwordreset#141]
Currently I have this implementation:

```
urlpatterns = [
    ...
    url(r'^api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    ...
]
```
Then when a user requests a password reset I send an email using the Signal provided by the package:

```
@receiver(reset_password_token_created)
def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
    """
    Handles password reset tokens
    When a token is created, an e-mail needs to be sent to the user
    :param reset_password_token: Token Model Object
    :return:
    """
    # send an e-mail to the user
    context = {
        'email': reset_password_token.user.email,
        'reset_password_url': f"{BASE_URL}new-password?token={reset_password_token.key}"
    }
    send_reset_pwd_to_sendingblue.delay(context)
```
However, in my case, I want to programmatically create the token and send it to the user without the use of the endpoint meaning the user won't reset their password through the endpoint, rather my application will create the token and send it to the user.

**Comment by cyzanfar** [comment]
Any help here pleaseeee?

**Comment by nezhar** [comment]
Have you tried to create a [custom token generator](https://github.com/anexia-it/django-rest-passwordreset#custom-token-generator)?

**Comment by nezhar** [comment]
Can you also describe your use case a bit? After looking a second time it sound more like you need another trigger for the reset, other then the [rest endpoint](https://github.com/anexia-it/django-rest-passwordreset/blob/master/django_rest_passwordreset/views.py#L99).

**Comment by cyzanfar** [comment]
Yes my usecase is when a user signs up (without the need of a password) I would like to send them a welcome email containing the reset password link. How can I go about doing that by leveraging the current implementation of the package and without creating my own token generator?
Can one only create a token via the endpoint?

**Comment by nezhar** [comment]
At the moment the library supports the creation of the token only with the endpoint. The custom token generator won't help here. A refactoring of [`ResetPasswordRequestToken.post`](https://github.com/anexia-it/django-rest-passwordreset/blob/master/django_rest_passwordreset/views.py#L99) where the `request` and the `serailizer` are detached form the password resert logic is required in order to achieve it. This way code can be moved into a new function which can be included for a custom reset. Would you like to try this and provide a pull request?

**Comment by nezhar** [comment]
It seems that there is already a similar PR available https://github.com/anexia-it/django-rest-passwordreset/pull/97

**Comment by nezhar** [comment]
In https://github.com/anexia-it/django-rest-passwordreset/pull/143 you can find a draft for the implementation.
This would allow you to use `generate_token_for_email` without the need of a request.

**Comment by Elkasitu** [comment]
In case someone else runs into this issue, you can simply do something like this:

```
from django_rest_passwordreset.models import ResetPasswordToken
from django.contrib.auth.models import User

my_user = User.objects.get(pk=1)
token = ResetPasswordToken.objects.create(user=my_user)
# do whatever you want with token.key here
```

**Comment by anx-abruckner** [comment]
Since #181 has been merged, this issue will be closed.
