### ISSUE TITLE
Poetry reads version as 0.0.0

### ISSUE THREAD

**Issue by wieczorek1990** [anexia-it/django-rest-passwordreset#161]
Version should be static string or read from file VERSION.

https://github.com/anexia-it/django-rest-passwordreset/blob/ceeb951d9047b56419a2ac89dae0600f8e999bd7/setup.py#L13

**Comment by nezhar** [comment]
We had this in the past and we moved away from it so we can automate the releases and keep them in sync with the tags. The [PACKAGE_VERSION](https://github.com/anexia-it/django-rest-passwordreset/blob/master/.github/workflows/publish.yml#L28) variable is defined in the workflow.

I asume you have this issue when installing the package via GitHub. I would sugest to fork the repository and set the default version in your fork as a workaround.
