### ISSUE TITLE
Is it possible add password reset form to email? 

### ISSUE THREAD

**Issue by alfredogama** [anexia-it/django-rest-passwordreset#166]
Hello,

In the example of the email for reset, I get a link like  http://127.0.0.1:8000/api/auth/reset/confirm/?token=xxxxxxxx.
Is it possible to set a form and not the DRF default API viewer?

**Comment by nezhar** [comment]
This depends on the way your application is build, the package will only provide you the REST API for the password reset.
You can either create a [custom view](https://docs.djangoproject.com/en/3.2/topics/http/views/) or you create a form in a UI App to which you can link in the email.

Here you can find an example using Django in combination with Angular:
- Django signal: https://github.com/snypy/snypy-backend/blob/master/snypy/users/signals.py#L21
- Angular component: https://github.com/snypy/snypy-frontend/blob/master/src/app/components/set-password/set-password.component.ts
