### ISSUE TITLE
REMOTE_ADDR not set (nginx, gunicorn and unix socket)

### ISSUE THREAD

**Issue by goiaba** [anexia-it/django-rest-passwordreset#61]
The `REMOTE_ADDR` value is used to set the `ip_address` of a new instance of  `ResetPasswordToken` class. Unfortunately, as state in [this](https://github.com/benoitc/gunicorn/issues/797#issuecomment-46652557) gunicorn issue, "... an unix socket has no remote address any more to comply with the CGI/WSGI spec.".

As a consequence, the persistence of the `ResetPasswordToken` throws an `NotNullViolation` exception, because `ip_address` is empty.

I see that you have introduced the `DJANGO_REST_PASSWORDRESET_REMOTE_ADDR` variable in the [code](https://github.com/anx-ckreuzberger/django-rest-passwordreset/blob/96e234114b494c40c375533bc8006961c2097c4f/django_rest_passwordreset/views.py#L146), but as far as I could understand, this does not solve the problem because its hard coded value (set in the settings.py) will be used as the default value when `REMOTE_ADDR` does not exists in `request.META`.

So I'm wondering if it would be a good idea to allow developer to specify the variable (s)he wants to grab from `request.META` in order to fill `ip_address` variable.

**Comment by anx-ckreuzberger** [comment]
This feature is already "kind-of" there, there is a PR for it: #58

**Comment by goiaba** [comment]
Nice, Christian. Any idea of how long to the changes be available in a stable release?

**Comment by anx-ckreuzberger** [comment]
This feature has been released on PyPi in version 1.1.0rc3.

You should be able install and test it using
```bash
pip install django-rest-passwordreset==1.1.0rc3
```

**Comment by anx-hnezbeda** [comment]
I close this as [1.1.0](https://github.com/anexia-it/django-rest-passwordreset/releases/tag/1.1.0) has been released.
