### ISSUE TITLE
DJANGO_REST_PASSWORDRESET_NO_INFORMATION_LEAKAGE switch not working

### ISSUE THREAD

**Issue by mindrunner** [anexia-it/django-rest-passwordreset#68]
I put 
`DJANGO_REST_PASSWORDRESET_NO_INFORMATION_LEAKAGE = True`
to settings.py
However, I am getting a 400 with this response:
```
{
    "email": [
        "There is no active user associated with this e-mail address or the password can not be changed"
    ]
}
```

What am I doing wrong?

**Comment by mikicz** [comment]
I checked the code and the settings is not used at all it seems

**Comment by anx-hnezbeda** [comment]
The anti information leakage is avaialable since 1.1.0rc2.
Today we release 1.1.0 which should work as documented.
