### ISSUE TITLE
Basic usage questions... maybe a request for the docs?

### ISSUE THREAD

**Issue by kohlab** [anexia-it/django-rest-passwordreset#75]
Please forgive the newbie questions, but I'm trying to understand how this library is supposed to be used.  I see that a call to the reset_password endpoint will generate a token and a signal, enabling a function to send an email to the given email address with that token in it.  I presume that when the user clicks the link in the email, they can then be presented with a form to fill in a new password.  What I don't get is:

- What endpoint should be in that initial email?  The example in the documentation uses reverse('password_reset:reset-password-request').  But wouldn't that just be a circular loop, since that's the endpoint that generated the email in the first place?  

- How can links access the endpoints in this library as POSTs, as they require?  At least in plain text emails, when clicked these only seem to show up as GETs.  

- Perhaps somebody can explain the basic data flow for how these endpoints should be used?  What is provided, what must be written?

Thanks!

**Comment by Cheesy008** [comment]
Hello, i also didn't get how to send this token to fronted. Have you found out something?

**Comment by kohlab** [comment]
I ended up ditching this for django-allauth and django-rest-auth, which I found to be much more useful for me.
