### ISSUE TITLE
Django 3.0 is not compatible with extension

### ISSUE THREAD

**Issue by MuslimBeibytuly** [anexia-it/django-rest-passwordreset#78]
celery      |   File "/usr/local/lib/python3.8/site-packages/django_rest_passwordreset/models.py", line 3, in <module>
celery      |     from django.utils.encoding import python_2_unicode_compatible
celery      | ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/usr/local/lib/python3.8/site-packages/django/utils/encoding.py)

**Comment by pakond** [comment]
same problem here

**Comment by Close0** [comment]
+1

**Comment by anx-hnezbeda** [comment]
#76 solves this issue

**Comment by frankyjquintero** [comment]
@anx-hnezbeda new realease please for support Django 3.0

**Comment by emilyemorehouse** [comment]
#80 is also required for Django 3.0 support (you'll see a `psycopg2.errors.InvalidTableDefinition: multiple primary keys for table "django_rest_passwordreset_resetpasswordtoken" are not allowed` error otherwise).

**Comment by chekroA** [comment]
Hi @anx-hnezbeda thank you for maintaining the porject so far. Could you please make a new release which will allow us to use ithank you :smile_cat:

**Comment by anx-hnezbeda** [comment]
We made the [1.1.0](https://pypi.org/project/django-rest-passwordreset/) release today. This release includes #76 and #80

**Comment by yhoiseth** [comment]
Thanks a lot 😃

**Comment by tiago-peres** [comment]
For any particular reason this issue is still "Open"?

**Comment by neoCheck** [comment]
No, I think it should be closed. The issue was resolved in the 1.1.0 release. Thank you

**Comment by anx-hnezbeda** [comment]
Yes it can be closed :slightly_smiling_face:
