### ISSUE TITLE
Stuck in migrate command

### ISSUE THREAD

**Issue by jmunera-lean** [anexia-it/django-rest-passwordreset#81]
Hi, I try to install de extension and configurate, but when pass through migrations, the first one runs without problems but the command get stuck in the second. Has been running for 1 hour without result.

**Comment by anx-hnezbeda** [comment]
This may be an issue related to 1.0.0
We have just released 1.1.0 which should fix this behavior.

**Comment by glothos** [comment]
Having the same problem on 1.2.1

Django==3.1
django-rest-passwordreset==1.2.1
djangorestframework==3.12.2
djangorestframework-simplejwt==4.6.0

Second migrations just gets stuck.
