### ISSUE TITLE
ImportError: No module named django_rest_passwordreset

### ISSUE THREAD

**Issue by Ebtessam** [anexia-it/django-rest-passwordreset#85]
Hello lovely day,

I am working on a very old codebase with django 1.8 and python 2.7 on a venv.  I am using version 0.9.7 which should be compatible, am I missing something? was django1.8 support dropped for this package?

`ImportError: No module named django_rest_passwordreset`

Here's part of my pip2 freeze
`django-rest-passwordreset==0.9.7
django-sendfile==0.3.10
django-taggit==0.22.1
django-test-without-migrations==0.6
django-treebeard==4.2.0
djangorestframework==3.6.0
djangorestframework-recursive==0.1.1
`

**Comment by anx-hnezbeda** [comment]
0.9.7 is compatible with 1.8 and python 2.7, we also had this in our CI pipeline for that release: https://travis-ci.org/anexia-it/django-rest-passwordreset/builds/442525968

Are you using multiple environments? It looks like the module is not installed in the env you run Django.

**Comment by Ebtessam** [comment]
I believe it is installed in my venv which is (ma7alpy2) which is the only one that is activated. If the module doesn't exist it would fail to import. I'm not sure what other data would help with solving the issue.
`
(ma7alpy2) ➜  ma7al git:(dockerDevRevert) ✗ python -c "import django_rest_passwordreset"
(ma7alpy2) ➜  ma7al git:(dockerDevRevert) ✗ echo $?
0
(ma7alpy2) ➜  ma7al git:(dockerDevRevert) ✗ python -c "import django_blah_blah"         
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named django_blah_blah

`

**Comment by Ebtessam** [comment]
Oops I think I'm just not in the correct docker container I need to check and I so I will just close this issue as soon I know.
