### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by thedatamineio** [anexia-it/django-rest-passwordreset#94]
I have followed everything in the docs. But it is not sending me the email i am using console backend.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

Can you please help with complete example i don't know where i am messing up.

Thank you

**Comment by havocy28** [comment]
I had the same issue and came accross this, which solved it for me:


[https://stackoverflow.com/questions/49697705/issues-printing-django-email-to-console]

Essentially, you just need to setup the smtp information, even if you're not using it.  Here's the example code you can copy and paste:

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'myemailaddress@gmail.com'
EMAIL_HOST_PASSWORD = 'mypassword'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

**Comment by anx-cbenke** [comment]
@thedatamineio have you been able to resolve your problem?

**Comment by thedatamineio** [comment]
yes, thank you
