### ISSUE TITLE
django.urls.exceptions.NoReverseMatch: Reverse for '/api/password_reset/?token=***********' not found. '/api/password_reset/?token=***********' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by ominaik7** [anexia-it/django-rest-passwordreset#96]
This happens while generating the token and signal is sent to "password_reset_token_created" method

receiving error on highlighted bold text
context = {
        'current_user': reset_password_token.user,
        'username': reset_password_token.user.username,
        'email': reset_password_token.user.email,
        **'reset_password_url': "{}?token={}".format(reverse('password_reset:reset-password-request'), reset_password_token.key)**
    }

**Comment by loganknecht** [comment]
@ominaik7 Were you able to solve this?
